#!/bin/bash

cp /var/lib/k0s/pki/admin.conf ~/admin.conf
. _env

#metalb 
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.10.2/manifests/namespace.yaml
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.10.2/manifests/metallb.yaml

#metallb ip external pool
kubectl apply -f manifests/metallb.yml

kubectl apply -f manifests/rethinkdb.yml

helm install farm ./manifests/openstf/
